frontend:
  build:
    context: .
    dockerfile: Dockerfile.frontend
  ports:
    - "3000:3000"
  environment:
    - NODE_ENV=development
    - NEXT_PUBLIC_GRAPHQL_ENDPOINT=http://backend:8080/query
  volumes:
    - .:/app
    - /app/node_modules
    - /app/.next
  depends_on:
    - backend
  command: yarn dev

backend:
  build:
    context: ./backend
    dockerfile: Dockerfile.backend
  ports:
    - "8080:8080"
  environment:
    - PORT=8080
  volumes:
    - ./backend:/app
  working_dir: /app

networks:
  default:
    driver: bridge
